# Generated by Django 5.2.7 on 2025-10-07 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Group', models.CharField(blank=True, max_length=100)),
                ('Number', models.CharField(blank=True, max_length=50, unique=True)),
                ('Mobile', models.CharField(blank=True, max_length=20)),
                ('Email', models.EmailField(blank=True, max_length=254)),
                ('Status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('PENDING', 'Pending')], default='ACTIVE', max_length=10)),
                ('Active', models.BooleanField(default=True)),
                ('CreditLimit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('PaymentTerms', models.CharField(blank=True, max_length=100)),
                ('Salesman', models.CharField(blank=True, max_length=150)),
                ('DefaultPriority', models.IntegerField(default=5)),
                ('AlertNotes', models.TextField(blank=True)),
                ('QuickBooksClassName', models.CharField(blank=True, max_length=255)),
                ('IssuableStatus', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAndTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TaxRate', models.DecimalField(decimal_places=3, default=0.0, max_digits=5)),
                ('TaxExempt', models.BooleanField(default=False)),
                ('TaxExemptNumber', models.CharField(blank=True, max_length=100)),
                ('URL', models.URLField(blank=True)),
                ('CarrierName', models.CharField(blank=True, max_length=100)),
                ('CarrierService', models.CharField(blank=True, max_length=100)),
                ('ShippingTerms', models.CharField(blank=True, max_length=100)),
                ('ToBeEmailed', models.BooleanField(default=False)),
                ('ToBePrinted', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_tax', to='main_app.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AddressName', models.CharField(help_text="e.g., 'Primary Shipping', 'Billing'", max_length=255)),
                ('Address', models.CharField(max_length=255)),
                ('City', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('Zip', models.CharField(max_length=20)),
                ('Country', models.CharField(max_length=100)),
                ('AddressType', models.CharField(choices=[('RES', 'Residential'), ('MAIN', 'Main'), ('HOME', 'Home'), ('WORK', 'Work'), ('OTHER', 'Other')], default='OTHER', max_length=5)),
                ('IsDefault', models.BooleanField(default=False)),
                ('AddressContact', models.CharField(blank=True, help_text='Contact person at this location', max_length=255)),
                ('Contact', models.CharField(blank=True, help_text='Generic Contact', max_length=20)),
                ('Home', models.CharField(blank=True, max_length=20)),
                ('Work', models.CharField(blank=True, max_length=20)),
                ('Fax', models.CharField(blank=True, max_length=20)),
                ('Pager', models.CharField(blank=True, max_length=20)),
                ('Web', models.URLField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='main_app.userprofile')),
            ],
        ),
    ]
