# Generated by Django 5.2.7 on 2025-10-08 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='Contact',
        ),
        migrations.RemoveField(
            model_name='address',
            name='Fax',
        ),
        migrations.RemoveField(
            model_name='address',
            name='Home',
        ),
        migrations.RemoveField(
            model_name='address',
            name='Pager',
        ),
        migrations.RemoveField(
            model_name='address',
            name='Web',
        ),
        migrations.RemoveField(
            model_name='address',
            name='Work',
        ),
        migrations.RemoveField(
            model_name='shippingandtax',
            name='ToBeEmailed',
        ),
        migrations.RemoveField(
            model_name='shippingandtax',
            name='ToBePrinted',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Fax',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Home',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Main',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Other',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Pager',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Residential',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ToBeEmailed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ToBePrinted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Web',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Work',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
