# Generated by Django 5.2.7 on 2025-10-08 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_address_contact_remove_address_fax_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='Fax',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='Home',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='Main',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='Other',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='Pager',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='Residential',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='ToBeEmailed',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='ToBePrinted',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='Web',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='Work',
        ),
        migrations.AddField(
            model_name='address',
            name='Fax',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='Pager',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='Web',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shippingandtax',
            name='ToBeEmailed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shippingandtax',
            name='ToBePrinted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='address',
            name='AddressContact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='AddressName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='address',
            name='AddressType',
            field=models.CharField(blank=True, choices=[('RES', 'Residential'), ('MAIN', 'Main'), ('HOME', 'Home'), ('WORK', 'Work'), ('OTHER', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shippingandtax',
            name='CarrierName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shippingandtax',
            name='CarrierService',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shippingandtax',
            name='ShippingTerms',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shippingandtax',
            name='TaxExemptNumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shippingandtax',
            name='TaxRate',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='shippingandtax',
            name='URL',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='AlertNotes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='CreditLimit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='DefaultPriority',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='IssuableStatus',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='PaymentTerms',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='QuickBooksClassName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Salesman',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
